print("World,Hello")
name=input("ENTER YOUR NAME : ")
print("Hello ", name)
email = input("Enter your email address")
print("Email", email)
phone = input("Enter your phone number")
print("Phone", phone)